"""strecke

Revision ID: 46c4b8e25d3c
Revises: 
Create Date: 2024-03-16 19:10:14.861023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c4b8e25d3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bahnhof',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('adresse', sa.String(length=256), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('strecke',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('abschnitt',
    sa.Column('abschnitt_id', sa.Integer(), nullable=False),
    sa.Column('startbahnhof_id', sa.String(length=64), nullable=True),
    sa.Column('endbahnhof_id', sa.String(length=64), nullable=True),
    sa.Column('strecke_id', sa.String(length=64), nullable=True),
    sa.Column('maximale_geschwindigkeit', sa.Integer(), nullable=True),
    sa.Column('maximale_spurweite', sa.Integer(), nullable=True),
    sa.Column('nutzungsentgelt', sa.Integer(), nullable=True),
    sa.Column('distanz', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['endbahnhof_id'], ['bahnhof.name'], ),
    sa.ForeignKeyConstraint(['startbahnhof_id'], ['bahnhof.name'], ),
    sa.ForeignKeyConstraint(['strecke_id'], ['strecke.name'], ),
    sa.PrimaryKeyConstraint('abschnitt_id')
    )
    op.create_table('warnung',
    sa.Column('warnung_id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=64), nullable=True),
    sa.Column('gueltigkeitsdatum', sa.Date(), nullable=True),
    sa.Column('beschreibung', sa.String(length=256), nullable=True),
    sa.Column('abschnitt_id_warnung', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['abschnitt_id_warnung'], ['abschnitt.abschnitt_id'], ),
    sa.PrimaryKeyConstraint('warnung_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warnung')
    op.drop_table('abschnitt')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('strecke')
    op.drop_table('bahnhof')
    # ### end Alembic commands ###
