"""warnung boolean

Revision ID: 938cae3c571f
Revises: 46c4b8e25d3c
Create Date: 2024-03-17 16:59:57.910556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938cae3c571f'
down_revision = '46c4b8e25d3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abschnitt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warnung', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abschnitt', schema=None) as batch_op:
        batch_op.drop_column('warnung')

    # ### end Alembic commands ###
