"""warnung bol

Revision ID: c79b14107691
Revises: d24af21cedcf
Create Date: 2024-03-17 17:07:04.991324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c79b14107691'
down_revision = 'd24af21cedcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abschnitt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warnung', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abschnitt', schema=None) as batch_op:
        batch_op.drop_column('warnung')

    # ### end Alembic commands ###
