"""warnung backref

Revision ID: d24af21cedcf
Revises: 938cae3c571f
Create Date: 2024-03-17 17:01:48.858560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24af21cedcf'
down_revision = '938cae3c571f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abschnitt', schema=None) as batch_op:
        batch_op.drop_column('warnung')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abschnitt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warnung', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
