"""wartung table

Revision ID: 0451f47a85d6
Revises: b1895c63b6ba
Create Date: 2024-05-17 20:11:00.108539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0451f47a85d6'
down_revision = 'b1895c63b6ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wartung',
    sa.Column('wartung_nr', sa.String(), nullable=False),
    sa.Column('mitarbeiter_id', sa.Integer(), nullable=False),
    sa.Column('zug_nummer', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mitarbeiter_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zug_nummer'], ['zug.zug_nummer'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('wartung_nr'),
    sa.UniqueConstraint('mitarbeiter_id', 'start_time', name='uq_mitarbeiter_time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wartung')
    # ### end Alembic commands ###
